### ISSUE TITLE
Allow Custom Configuration

### ISSUE THREAD

**Issue by MondayMorningHaskell** [MondayMorningHaskell/haskellings#16]
Right now configuration is hard-coded to look in particular places for GHC executables and Stack package DBs (e.g. `~/.stack`). Add a `haskellings configure` command that will allow the user to customize the directory to search for the items, in case a user has a custom installation of Haskell.

**Comment by jhb563** [comment]
Addressed by https://github.com/MondayMorningHaskell/haskellings/pull/28
