### ISSUE TITLE
NIx support

### ISSUE THREAD

**Issue by RosarioPulella** [MondayMorningHaskell/haskellings#29]
I could be useful to have a `shell.nix` file that sets up an environment with `haskellings` already in the path and maybe setup editor integration.

**Comment by MondayMorningHaskell** [comment]
Interesting idea! I'm still not super familiar with Nix, but I'll probably be able to give this a try at some point.

**Comment by RosarioPulella** [comment]
I opened this because I was having trouble using setting this repo up on NixOS (something was having trouble finding ghc). I did a bunch of investigating I can help at least make this easier for nix/NixOS users. I will try to do some more investigating and get some specific details this week. 

I would like to help as much as possible, I really want to use this project and once I have figured out enough I can submit a more specific issue and maybe a PR.

**Comment by MondayMorningHaskell** [comment]
Sounds good! I'd be happy to take a look and help test if you open a PR :)

**Comment by RosarioPulella** [comment]
It seems like they someone wants to do something similar for the rustlings project.

https://github.com/rust-lang/rustlings/issues/683

Their work can help here. Also the motivations in that issue that the user describes are much the same here.

**Comment by jakeisnt** [comment]
I can set this up here if you'd like me to! Cabal2nix is an excellent tool.

**Comment by RosarioPulella** [comment]
That would be awesome @jakeisnt! 😃 I was trying to figure it out for myself a few days back and was having trouble, I am very interested in what your solution will look like.

**Comment by jakeisnt** [comment]
Sure - [here's what I have so far](https://github.com/jakeisnt/haskellings). 

The package is successfully compiling but it looks like the test suite is currently failing trying to find GHC or the project root. 
I can't figure out why! Are the tests successful normally?

**Comment by jakeisnt** [comment]
Ah, looks like this is a lot more complicated than I thought.

Here's why the tests won't work - and why a Nix build may not be a good idea either:
```
In order to run exercises, Haskellings needs to know two paths on the local system.

    The path to the appropriate version of GHC (currently 8.8.4)
    The path to a Stack snapshot package DB for that GHC version. This package DB must contain any dependencies that are needed for the exercises, particularly tasty and tasty-hunit which are used for unit testing exercise functions.
```

Notably, the fact that these paths are both typically found outside of the current repository will make the tests fail. Nix, when building packages, typically runs in pure evaluation mode -- this means that its access to your system is constrained to the contents of the repository. Aside from the obvious security concerns, this is done to guarantee reproducibility -- if the package depends on files living outside of the source code on an installer's computer, the Nix build will likely not be reproducible.

I think that there's a way to prevent the Nix build from running tests, but I wasn't able to figure it out in a reasonable amount of time -- and I think that tests should be run, as given the current `haskelling` design you require the guarantee that the end user has the proper stack libraries and GHC on their path. As such, to properly add a Nix build to this project, it's likely that it needs a substantial rework (if it's even possible). I honestly do not have the knowledge of Nix or Haskell to do this for this project.

I could make a quick `shell.nix` that would install the right GHC/Stack versions and run `stack build` right away but I'm not sure how much value that brings to the project.

**Comment by RosarioPulella** [comment]
Interesting, I think the issue with finding ghc and a stack snapshot package db could be solve by generating the config file for haskellings. https://github.com/MondayMorningHaskell/haskellings#custom-configuration with the paths to the derivations for ghc and a stack snapshot package db.

**Comment by RosarioPulella** [comment]
Getting the stack snapshot package db in a derivation might be the tricky part. @jakeisnt If you continue to get stumped I can try somethings.

**Comment by jakeisnt** [comment]
I got it to work with a hacky shell.nix - check the PR! I'm looking at making the buildmore robust now.

**Comment by jakeisnt** [comment]
PR's ready now! #34
