### ISSUE TITLE
Add description, tags, and template project to haskellings repo settings

### ISSUE THREAD

**Issue by jakeisnt** [MondayMorningHaskell/haskellings#35]
Motivations:
- description, tags: Make the repository easier to find!
- template project: A common pattern with `ziglings` and `rustlings` is to fork the code and work on the solutions on the fork so that the work - and whatever notes come with it - can be preserved on GitHub. Providing the option to use this codebase as a template repository instead provides an easy way for participants who may have no interest in contributing changes back to the repo to make a copy of it!

**Comment by MondayMorningHaskell** [comment]
@jakeisnt I updated the description and enabled Template repository.

When you say "tags" do you mean "topics"? I added a few topics to the Repository description, but I'm not sure if you mean adding more tagged branches.

**Comment by jakeisnt** [comment]
I meant topics, my bad! Thanks for doing this.

**Comment by jhb563** [comment]
👍
