### ISSUE TITLE
Unable to call `haskellings` on windows

### ISSUE THREAD

**Issue by damien-biasotto** [MondayMorningHaskell/haskellings#46]
I tried to run `haskellings` on windows either with `haskellings watch` or `haskellings run XXX` but the same error message is shown:
> Couldn't find an appropriate stack package DB!

**Comment by MondayMorningHaskell** [comment]
On your Windows system, is the environment `STACK_ROOT` set? If so, when you navigate to that directory, you should find a sub-folder `snapshots`, where each sub-directory then is a hash of sorts.

Mine is located at `C:\sr`, but I suppose the location could be different, or the environment variable might not be set properly depending how Stack was installed.

**Comment by damien-biasotto** [comment]
Oh yeah, it is probably linked to my stack setup on windows. I don't think I have this env variable set.

I close this issue and will give it another try once I'm on a windows machine again :)
